### ISSUE TITLE
existingSecret and existingSecretPasswordKey are ignored

### ISSUE THREAD

**Issue by gajus** [airbytehq/helm-charts#6]
Our configuration:

```yaml
airbyte:
  externalDatabase:
    database: airbyte
    existingSecret: contra-airbyte
    existingSecretPasswordKey: POSTGRES_PASSWORD
    host: '...'
    port: 5432
    user: postgres
```

However, when the bootloader is starting, it is throwing an error:

```
Error: couldn't find key DATABASE_PASSWORD in Secret airbyte/contra-airbyte-airbyte-secrets
```

Meanwhile, I would expect the `DATABASE_PASSWORD` to be pulled from `contra-airbyte` secret.
